function startGUIStars()
  local x, y = guiGetScreenSize()
  right = x
  bottom = y
  starBackOne = guiCreateStaticImage(right - right * 0.223, bottom - bottom * 0.77, 32, 32, "images/starback.png", false)
  starBackTwo = guiCreateStaticImage(right - right * 0.195, bottom - bottom * 0.77, 32, 32, "images/starback.png", false)
  starBackThree = guiCreateStaticImage(right - right * 0.167, bottom - bottom * 0.77, 32, 32, "images/starback.png", false)
  starBackFour = guiCreateStaticImage(right - right * 0.139, bottom - bottom * 0.77, 32, 32, "images/starback.png", false)
  starBackFive = guiCreateStaticImage(right - right * 0.11, bottom - bottom * 0.77, 32, 32, "images/starback.png", false)
  starBackSix = guiCreateStaticImage(right - right * 0.083, bottom - bottom * 0.77, 32, 32, "images/starback.png", false)
  starOne = guiCreateStaticImage(right - right * 0.223, bottom - bottom * 0.77, 32, 32, "images/star.png", false)
  starTwo = guiCreateStaticImage(right - right * 0.195, bottom - bottom * 0.77, 32, 32, "images/star.png", false)
  starThree = guiCreateStaticImage(right - right * 0.167, bottom - bottom * 0.77, 32, 32, "images/star.png", false)
  starFour = guiCreateStaticImage(right - right * 0.139, bottom - bottom * 0.77, 32, 32, "images/star.png", false)
  starFive = guiCreateStaticImage(right - right * 0.11, bottom - bottom * 0.77, 32, 32, "images/star.png", false)
  starSix = guiCreateStaticImage(right - right * 0.083, bottom - bottom * 0.77, 32, 32, "images/star.png", false)
  guiSetVisible(starOne, false)
  guiSetVisible(starTwo, false)
  guiSetVisible(starThree, false)
  guiSetVisible(starFour, false)
  guiSetVisible(starFive, false)
  guiSetVisible(starSix, false)
  guiSetVisible(starBackOne, true)
  guiSetVisible(starBackTwo, true)
  guiSetVisible(starBackThree, true)
  guiSetVisible(starBackFour, true)
  guiSetVisible(starBackFive, true)
  guiSetVisible(starBackSix, true)
  triggerServerEvent("checkWanted",getLocalPlayer())
end
addEventHandler("onClientResourceStart", getResourceRootElement(), startGUIStars)

function setClientWantedLevel(l_2_0)
  l_2_0 = tonumber(l_2_0)
  setElementData(getLocalPlayer(),"wanted",l_2_0)
  playSoundFrontEnd(13)
  triggerServerEvent("setNametag",getLocalPlayer(),getLocalPlayer(),getPlayerName(getLocalPlayer()),l_2_0)
  if l_2_0 == 0 or not l_2_0 then
    guiSetVisible(starOne, false)
    guiSetVisible(starTwo, false)
    guiSetVisible(starThree, false)
    guiSetVisible(starFour, false)
    guiSetVisible(starFive, false)
    guiSetVisible(starSix, false)
  elseif l_2_0 == 1 then
    guiSetVisible(starOne, true)
    guiSetVisible(starTwo, false)
    guiSetVisible(starThree, false)
    guiSetVisible(starFour, false)
    guiSetVisible(starFive, false)
    guiSetVisible(starSix, false)
  elseif l_2_0 == 2 then
    guiSetVisible(starOne, true)
    guiSetVisible(starTwo, true)
    guiSetVisible(starThree, false)
    guiSetVisible(starFour, false)
    guiSetVisible(starFive, false)
    guiSetVisible(starSix, false)
  elseif l_2_0 == 3 then
    guiSetVisible(starOne, true)
    guiSetVisible(starTwo, true)
    guiSetVisible(starThree, true)
    guiSetVisible(starFour, false)
    guiSetVisible(starFive, false)
    guiSetVisible(starSix, false)
  elseif l_2_0 == 4 then
    guiSetVisible(starOne, true)
    guiSetVisible(starTwo, true)
    guiSetVisible(starThree, true)
    guiSetVisible(starFour, true)
    guiSetVisible(starFive, false)
    guiSetVisible(starSix, false)
  elseif l_2_0 == 5 then
    guiSetVisible(starOne, true)
    guiSetVisible(starTwo, true)
    guiSetVisible(starThree, true)
    guiSetVisible(starFour, true)
    guiSetVisible(starFive, true)
    guiSetVisible(starSix, false)
  elseif l_2_0 == 6 then
    guiSetVisible(starOne, true)
    guiSetVisible(starTwo, true)
    guiSetVisible(starThree, true)
    guiSetVisible(starFour, true)
    guiSetVisible(starFive, true)
    guiSetVisible(starSix, true)
  end
end
addEvent("setClientWantedLevel",true)
addEventHandler("setClientWantedLevel",getRootElement(),setClientWantedLevel)